/*
 * THIS FILE IS AUTOMATICALLY GENERATED
 *
 * I2C-Generator: 0.3.0
 * Yaml Version: 0.1.0
 * Template Version: 0.7.0-62-g3d691f9
 */
/*
 * Copyright (c) 2021, Sensirion AG
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are met:
 *
 * * Redistributions of source code must retain the above copyright notice, this
 *   list of conditions and the following disclaimer.
 *
 * * Redistributions in binary form must reproduce the above copyright notice,
 *   this list of conditions and the following disclaimer in the documentation
 *   and/or other materials provided with the distribution.
 *
 * * Neither the name of Sensirion AG nor the names of its
 *   contributors may be used to endorse or promote products derived from
 *   this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
 * AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
 * ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE
 * LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
 * CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
 * SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
 * INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
 * CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
 * ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 */

#ifndef SENSIRIONI2CSGP41_H
#define SENSIRIONI2CSGP41_H
 #include <stdint.h>
// Minimal SGP41 C interface using project's `twi` library (no Arduino/Wire)

#ifdef __cplusplus
extern "C" {
#endif

/**
 * @brief  Execute conditioning phase on SGP41 sensor (10 seconds warm-up).
 * @param  defaultRh Relative humidity compensation value.
 * @param  defaultT  Temperature compensation value.
 * @param  srawVoc   Pointer to store raw VOC signal value.
 * @return 0 on success, error code otherwise.
 */
uint16_t sgp41_executeConditioning(uint16_t defaultRh, uint16_t defaultT,
                                   uint16_t* srawVoc);

/**
 * @brief  Measure raw VOC and NOx signals from SGP41 sensor.
 * @param  relativeHumidity Relative humidity compensation value.
 * @param  temperature      Temperature compensation value.
 * @param  srawVoc          Pointer to store raw VOC signal value (0–65535).
 * @param  srawNox          Pointer to store raw NOx signal value (0–65535).
 * @return 0 on success, error code otherwise.
 */
uint16_t sgp41_measureRawSignals(uint16_t relativeHumidity,
                                 uint16_t temperature, uint16_t* srawVoc,
                                 uint16_t* srawNox);

/**
 * @brief  Execute self-test on SGP41 sensor.
 * @param  testResult Pointer to store self-test result (0xD400 for pass).
 * @return 0 on success, error code otherwise.
 */                                
uint16_t sgp41_executeSelfTest(uint16_t* testResult);

/**
 * @brief  Turn off heater element in SGP41 sensor.
 * @return 0 on success, error code otherwise.
 */
uint16_t sgp41_turnHeaterOff(void);

/**
 * @brief  Read 48-bit serial number from SGP41 sensor.
 * @param  serialNumber Pointer to array of 3 x uint16_t to store serial number.
 * @return 0 on success, error code otherwise.
 */
uint16_t sgp41_getSerialNumber(uint16_t serialNumber[]);

#ifdef __cplusplus
}
#endif

#endif /* SENSIRIONI2CSGP41_H */